on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://www.treasury.gov/resource-center/data-chart-center/interest-rates/Datasets/yield.xml --output yieldcurve.xml
