on: push
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
#        args: -qO- https://httpbin.org/get
         args: https://www.treasury.gov/resource-center/data-chart-center/interest-rates/Datasets/yield.xml
         #--output 
