on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - name: download xml
      run:  curl https://www.treasury.gov/resource-center/data-chart-center/interest-rates/Datasets/yield.xml > yieldcurve.xml
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: jumblies.github.io/yieldcurve.xml
#         args: https://www.treasury.gov/resource-center/data-chart-center/interest-rates/Datasets/yield.xml --output 
